fix: noticket - fix broken pagination + version bump 0.6.20
3d4b752bda9d21215001e3772954446b0b64752b introduced a bug that caused
the following test to fail:

FAIL: test_pagination (tests.django_tests.QuerySetTest)
Ensure that Pagination works as expected
----------------------------------------------------------------------
Traceback (most recent call last):
  File
    "/home/vagrant/conv_libs/mongoengine/tests/django_tests.py",
    line 92, in test_pagination
      self.assertEqual(t.render(Context(d)), u'%d:%d:' % (start, end))
  AssertionError: u'3:4:5:6:' != u'3:4:'

Only in some very rare cases (that the Django Paginator exercised) was
paging/slicing broken. I couldn't get a reproducable test case that
showed the same behaviour outside of the Django Paginator :(