fix: noticket - fixes broken cursor ordering.
aa7cd5b564cdbfe15082eb476b19d8d27d0c64b8 broke the following test:

======================================================================
FAIL: test_ordering (tests.queryset.QuerySetTest)
    Ensure default ordering is applied and can be overridden.
    ----------------------------------------------------------------------
    Traceback (most recent call last):
          File "/home/vagrant/conv_libs/mongoengine/tests/queryset.py",
          line 755, in test_ordering
              self.assertEqual(latest_post.title, "Blog Post #3")
          AssertionError: u'Blog Post #1' != 'Blog Post #3'

This is because we were no longer calling sort() on the cursor after
calling order_by.